# Generated by Django 4.2.5 on 2023-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_franco', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ya_envio_formulario',
            field=models.CharField(default='enviado', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
