# Generated by Django 4.2.5 on 2023-10-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_franco', '0004_alter_proyecto_ya_envio_formulario_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='ya_envio_formulario',
        ),
    ]
